
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import tbaclient.NetwConfig;


/**
 *This is the main client view class
 * @author Joe
 *
 * @version $Rev:: 11            $ $Date:: 2009-07-21 #$
 */
public class mainclientview extends javax.swing.JFrame {

    /** Creates new form mainclientview */
    public mainclientview() {
        //initialise NetwConfig.blnproxyOn as off
        NetwConfig.initialise();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemQuickConnect = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemNetwConfig = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel11.setText("jLabel8");
        jLabel11.setBounds(640, 0, 150, 470);
        jPanel1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("jLabel8");
        jLabel8.setBounds(0, 0, 70, 470);
        jPanel1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });

        jLabel4.setText("Panel6");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel4)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel6.setBounds(100, 10, -1, -1);
        jPanel1.add(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });

        jLabel2.setText("Panel5");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel2)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel5.setBounds(100, 10, -1, -1);
        jPanel1.add(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });

        jLabel5.setText("Panel7");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel5)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel7.setBounds(100, 10, -1, -1);
        jPanel1.add(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });

        jLabel3.setText("Panel4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel3)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel4.setBounds(100, 10, -1, -1);
        jPanel1.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel8MouseDragged(evt);
            }
        });

        jLabel6.setText("Panel8");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel6)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel8.setBounds(100, 10, -1, -1);
        jPanel1.add(jPanel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });

        jLabel9.setText("Panel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel9)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel9)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel3.setBounds(100, 10, -1, -1);
        jPanel1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel9MouseDragged(evt);
            }
        });

        jLabel10.setText("Panel9");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel10)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel9.setBounds(100, 10, -1, -1);
        jPanel1.add(jPanel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");

        jMenuItemQuickConnect.setText("Quick Connect");
        jMenuItemQuickConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuickConnectActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemQuickConnect);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItemNetwConfig.setText("Network Settings");
        jMenuItemNetwConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNetwConfigActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemNetwConfig);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseDragged

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseDragged

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MousePressed

    private void jPanel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseDragged

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        offsetPanels();
        // TODO add your handling code here:
}//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        getMousePos();
        // TODO add your handling code here:
}//GEN-LAST:event_jPanel4MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MousePressed

    private void jPanel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseDragged

private void jMenuItemNetwConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNetwConfigActionPerformed
    // TODO add your handling code here:
    NetworkDialogue nd = new NetworkDialogue(this, true);
}//GEN-LAST:event_jMenuItemNetwConfigActionPerformed

private void jMenuItemQuickConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuickConnectActionPerformed
// TODO add your handling code here:
    QConnectDialogue qcd = new QConnectDialogue(this, true);
}//GEN-LAST:event_jMenuItemQuickConnectActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainclientview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemNetwConfig;
    private javax.swing.JMenuItem jMenuItemQuickConnect;
    private javax.swing.JLayeredPane jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
    private int prevPos = 0;

    private void getMousePos() {
       System.out.println(jPanel3.size());
       System.out.println(jPanel1.size());
        PointerInfo a = MouseInfo.getPointerInfo();
        Point b = a.getLocation();
        int x = (int) b.getX();
        prevPos = x;

        /////////////////
        Point tmp1 = new Point();
        Point tmp2 = new Point();
        tmp1 = jPanel3.getLocation();
        tmp2 = jPanel4.getLocation();
        System.out.println("jPanel4 - jPanel3 = "+(tmp2.x-tmp1.x));
        tmp1 = jPanel4.getLocation();
        tmp2 = jPanel5.getLocation();
        System.out.println("jPanel5 - jPanel4 = "+(tmp2.x-tmp1.x));
        tmp1 = jPanel5.getLocation();
        tmp2 = jPanel6.getLocation();
        System.out.println("jPanel6 - jPanel5 = "+(tmp2.x-tmp1.x));

        //jPanel3.setLocation(tmp);
    }

    private void offsetPanels(){
        int offset;

        PointerInfo a = MouseInfo.getPointerInfo();
        Point b = a.getLocation();
        int x = (int) b.getX();

        if (x>prevPos){
            offset = x - prevPos;
        }
        else{
            offset = x - prevPos;
        }

        Point tmp = new Point();
        
        tmp = jPanel3.getLocation();
        tmp.x += offset;
        jPanel3.setLocation(tmp);

        tmp = jPanel4.getLocation();
        tmp.x += offset;
        jPanel4.setLocation(tmp);

        tmp = jPanel5.getLocation();
        tmp.x += offset;
        jPanel5.setLocation(tmp);

        tmp = jPanel6.getLocation();
        tmp.x += offset;
        jPanel6.setLocation(tmp);

        tmp = jPanel7.getLocation();
        tmp.x += offset;
        jPanel7.setLocation(tmp);

        tmp = jPanel8.getLocation();
        tmp.x += offset;
        jPanel8.setLocation(tmp);

        tmp = jPanel9.getLocation();
        tmp.x += offset;
        jPanel9.setLocation(tmp);

        checkPanelPos();

        prevPos = x;

    }

    private void checkPanelPos(){
        int width, panel1Width;

        panel1Width = jPanel1.getWidth();
        width = jPanel3.getWidth();

        Point tmp = new Point();
        Point tmp1 = new Point();

        tmp = jPanel3.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel9.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel3.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel4.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel3.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel4.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel3.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel4.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel5.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel4.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel5.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel4.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel5.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel6.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel5.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel6.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel5.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel6.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel7.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel6.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel7.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel6.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel7.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel8.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel7.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel8.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel7.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel8.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel9.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel8.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel9.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel8.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel9.setLocation(tmp);
            //set the new pos coming from the right
        }
        //else if (tmp.x > panel1Width - width/2 ){
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel3.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel9.setLocation(tmp);
            //set the new pos coming from the left
        }
    }
    //[235,233,237] = original color
}