/*
 * NetworkDialogue.java
 *
 * Created on 14 August 2009, 13:19
 */



/**
 *
 * @author  charles
 */


import tbaclient.NetwConfig;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import java.lang.*;

import java.io.*;
import java.net.*;

import java.text.*;


public class NetworkDialogue extends javax.swing.JDialog {
    
    private String proxy;
    private int proxyPort;
    
    private String user;
    private String pass;
    
    private int timeOut;

    private boolean blnProxyOn;

    /** Creates new form NetworkDialogue */
    public NetworkDialogue(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        proxy = NetwConfig.getProxy();
        proxyPort = NetwConfig.getProxyPort();
        
        user=NetwConfig.getUser();
        pass=NetwConfig.getPass();
        
        timeOut = NetwConfig.getTimeOut();

        initComponents();
        
        //Enable/disable components
        txtProxy.setEnabled(chkProxyOn.isSelected());
        txtPort.setEnabled(chkProxyOn.isSelected());

        txtUser.setEnabled(chkProxyOn.isSelected());
        txtPass.setEnabled(chkProxyOn.isSelected());

        txtTimeOut.setEnabled(chkProxyOn.isSelected());

        //open in middle of screen
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();

        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        setLocation(x, y);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkProxyOn = new javax.swing.JCheckBox();
        txtProxy = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtTimeOut = new javax.swing.JTextField();
        jbOK = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Network Settings");

        chkProxyOn.setSelected(NetwConfig.isProxyOn());
        chkProxyOn.setText("Enable Proxy");
        chkProxyOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProxyOnActionPerformed(evt);
            }
        });

        txtProxy.setText(proxy);
        txtProxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProxyActionPerformed(evt);
            }
        });

        jLabel1.setText("Proxy Server: ");

        jLabel2.setText("Port:");

        txtPort.setText(Integer.toString(proxyPort));
        txtPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortActionPerformed(evt);
            }
        });

        jLabel3.setText("Username: ");

        jLabel4.setText("Password: ");

        jLabel5.setText("Timeout: ");

        txtUser.setText(user);

        txtTimeOut.setText(Integer.toString(timeOut));

        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        jbCancel.setText("Cancel");

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkProxyOn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPass)
                            .addComponent(txtUser)
                            .addComponent(txtTimeOut)
                            .addComponent(txtProxy, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancel)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkProxyOn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jbOK))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed
// TODO: nothing here

}//GEN-LAST:event_txtPortActionPerformed

private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
// TODO: 
    NetwConfig.setProxy(txtProxy.getText());
    NetwConfig.setProxyPort(Integer.parseInt(txtPort.getText()));
    
    NetwConfig.setUser(txtUser.getText());
    NetwConfig.setPass(new String(txtPass.getPassword()));

    NetwConfig.setProxyOn(chkProxyOn.isSelected());

    setVisible(false);
    //TODO: fix enable proxy checkbox

   /* try
    {

            //s = NetwConfig.getProxy("proxy.uow.edu.au", 8080);
            s = NetwConfig.getProxy(proxy, proxyPort);
            NetwConfig.Authenticate(user, pass);

            InetAddress ina = InetAddress.getByName("sun.java.com");
            SocketAddress connectTo = new InetSocketAddress(ina,8080);

            s.connect(connectTo,timeOut);

    } 
    catch (Exception temp)
    {
            System.out.println(temp.getMessage());
    }*/ 
}//GEN-LAST:event_jbOKActionPerformed

private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtPassActionPerformed

private void chkProxyOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProxyOnActionPerformed
    // TODO: enable/disable controls when clicked
    /*if (chkProxyOn.isSelected() == true)
    {
        //TODO: enable controls
        
    }
    else
    {
        //TODO: disable controls
    }*/

    txtProxy.setEnabled(chkProxyOn.isSelected());
    txtPort.setEnabled(chkProxyOn.isSelected());

    txtUser.setEnabled(chkProxyOn.isSelected());
    txtPass.setEnabled(chkProxyOn.isSelected());

    txtTimeOut.setEnabled(chkProxyOn.isSelected());


}//GEN-LAST:event_chkProxyOnActionPerformed

private void txtProxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProxyActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_txtProxyActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NetworkDialogue dialog = new NetworkDialogue(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkProxyOn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtProxy;
    private javax.swing.JTextField txtTimeOut;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    
    
    
    
    
    
}
