package tbaclient;


import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;


/**
 *This is the main client view class
 * @author Joe
 *
 * @version $Rev:: 11            $ $Date:: 2009-07-21 #$
 */
public class mainclientview extends javax.swing.JFrame {

    /** Creates new form mainclientview */
    public mainclientview() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel2 = new javax.swing.JPanel();
      jPanel1 = new javax.swing.JLayeredPane();
      jPanel3 = new javax.swing.JPanel();
      jPanel4 = new javax.swing.JPanel();
      jPanel5 = new javax.swing.JPanel();
      jPanel6 = new javax.swing.JPanel();
      jPanel7 = new javax.swing.JPanel();
      jPanel8 = new javax.swing.JPanel();
      jPanel9 = new javax.swing.JPanel();
      jPanel10 = new tbaclient.DayPanel();
      jToolBar1 = new javax.swing.JToolBar();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      jMenu2 = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 158, Short.MAX_VALUE)
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 463, Short.MAX_VALUE)
      );

      jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
      jPanel1.setAutoscrolls(true);

      jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            jPanel3MousePressed(evt);
         }
      });
      jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
         public void mouseDragged(java.awt.event.MouseEvent evt) {
            jPanel3MouseDragged(evt);
         }
      });

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 98, Short.MAX_VALUE)
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 388, Short.MAX_VALUE)
      );

      jPanel3.setBounds(80, 30, 100, 390);
      jPanel1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

      jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 98, Short.MAX_VALUE)
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 388, Short.MAX_VALUE)
      );

      jPanel4.setBounds(80, 30, 100, 390);
      jPanel1.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

      jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 98, Short.MAX_VALUE)
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 388, Short.MAX_VALUE)
      );

      jPanel5.setBounds(80, 30, 100, 390);
      jPanel1.add(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

      jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
      jPanel6.setLayout(jPanel6Layout);
      jPanel6Layout.setHorizontalGroup(
         jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 98, Short.MAX_VALUE)
      );
      jPanel6Layout.setVerticalGroup(
         jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 388, Short.MAX_VALUE)
      );

      jPanel6.setBounds(80, 30, 100, 390);
      jPanel1.add(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

      jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
      jPanel7.setLayout(jPanel7Layout);
      jPanel7Layout.setHorizontalGroup(
         jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 98, Short.MAX_VALUE)
      );
      jPanel7Layout.setVerticalGroup(
         jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 388, Short.MAX_VALUE)
      );

      jPanel7.setBounds(80, 30, 100, 390);
      jPanel1.add(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

      jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
      jPanel8.setLayout(jPanel8Layout);
      jPanel8Layout.setHorizontalGroup(
         jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 98, Short.MAX_VALUE)
      );
      jPanel8Layout.setVerticalGroup(
         jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 388, Short.MAX_VALUE)
      );

      jPanel8.setBounds(80, 30, 100, 390);
      jPanel1.add(jPanel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

      jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
      jPanel9.setLayout(jPanel9Layout);
      jPanel9Layout.setHorizontalGroup(
         jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 98, Short.MAX_VALUE)
      );
      jPanel9Layout.setVerticalGroup(
         jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 388, Short.MAX_VALUE)
      );

      jPanel9.setBounds(80, 30, 100, 390);
      jPanel1.add(jPanel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

      jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            jPanel10MousePressed(evt);
         }
      });
      jPanel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
         public void mouseDragged(java.awt.event.MouseEvent evt) {
            jPanel10MouseDragged(evt);
         }
      });
      jPanel10.setBounds(240, 10, 145, 436);
      jPanel1.add(jPanel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

      jToolBar1.setRollover(true);

      jMenu1.setText("File");
      jMenuBar1.add(jMenu1);

      jMenu2.setText("Edit");
      jMenuBar1.add(jMenu2);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(35, 35, 35)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MousePressed
    {//GEN-HEADEREND:event_jPanel3MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MouseDragged
    {//GEN-HEADEREND:event_jPanel3MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel4MousePressed
    {//GEN-HEADEREND:event_jPanel4MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel4MouseDragged
    {//GEN-HEADEREND:event_jPanel4MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel5MousePressed
    {//GEN-HEADEREND:event_jPanel5MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel5MouseDragged
    {//GEN-HEADEREND:event_jPanel5MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel6MousePressed
    {//GEN-HEADEREND:event_jPanel6MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel6MouseDragged
    {//GEN-HEADEREND:event_jPanel6MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseDragged

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel7MousePressed
    {//GEN-HEADEREND:event_jPanel7MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel7MouseDragged
    {//GEN-HEADEREND:event_jPanel7MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseDragged

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel8MousePressed
    {//GEN-HEADEREND:event_jPanel8MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MousePressed

    private void jPanel8MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel8MouseDragged
    {//GEN-HEADEREND:event_jPanel8MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseDragged

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel9MousePressed
    {//GEN-HEADEREND:event_jPanel9MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MousePressed

    private void jPanel9MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel9MouseDragged
    {//GEN-HEADEREND:event_jPanel9MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseDragged

    private void jPanel10MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel10MousePressed
    {//GEN-HEADEREND:event_jPanel10MousePressed
        getMousePos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MousePressed

    private void jPanel10MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel10MouseDragged
    {//GEN-HEADEREND:event_jPanel10MouseDragged
        offsetPanels();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseDragged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainclientview().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JLayeredPane jPanel1;
   private tbaclient.DayPanel jPanel10;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JPanel jPanel6;
   private javax.swing.JPanel jPanel7;
   private javax.swing.JPanel jPanel8;
   private javax.swing.JPanel jPanel9;
   private javax.swing.JToolBar jToolBar1;
   // End of variables declaration//GEN-END:variables
    private int prevPos = 0;

    private void getMousePos() {
       System.out.println(jPanel3.size());
       System.out.println(jPanel1.size());
        PointerInfo a = MouseInfo.getPointerInfo();
        Point b = a.getLocation();
        int x = (int) b.getX();
        prevPos = x;

        /////////////////
        Point tmp1 = new Point();
        Point tmp2 = new Point();
        tmp1 = jPanel3.getLocation();
        tmp2 = jPanel4.getLocation();
        System.out.println("jPanel4 - jPanel3 = "+(tmp2.x-tmp1.x));
        tmp1 = jPanel4.getLocation();
        tmp2 = jPanel5.getLocation();
        System.out.println("jPanel5 - jPanel4 = "+(tmp2.x-tmp1.x));
        tmp1 = jPanel5.getLocation();
        tmp2 = jPanel6.getLocation();
        System.out.println("jPanel6 - jPanel5 = "+(tmp2.x-tmp1.x));

        //jPanel3.setLocation(tmp);
    }

    private void offsetPanels(){
        int offset;

        PointerInfo a = MouseInfo.getPointerInfo();
        Point b = a.getLocation();
        int x = (int) b.getX();

        if (x>prevPos){
            offset = x - prevPos;
        }
        else{
            offset = x - prevPos;
        }

        Point tmp = new Point();
        
        tmp = jPanel3.getLocation();
        tmp.x += offset;
        jPanel3.setLocation(tmp);

        tmp = jPanel4.getLocation();
        tmp.x += offset;
        jPanel4.setLocation(tmp);

        tmp = jPanel5.getLocation();
        tmp.x += offset;
        jPanel5.setLocation(tmp);

        tmp = jPanel6.getLocation();
        tmp.x += offset;
        jPanel6.setLocation(tmp);

        tmp = jPanel7.getLocation();
        tmp.x += offset;
        jPanel7.setLocation(tmp);

        tmp = jPanel8.getLocation();
        tmp.x += offset;
        jPanel8.setLocation(tmp);

        tmp = jPanel9.getLocation();
        tmp.x += offset;
        jPanel9.setLocation(tmp);

        tmp = jPanel10.getLocation();
        tmp.x += offset;
        jPanel10.setLocation(tmp);
        checkPanelPos();

        prevPos = x;

    }

    private void checkPanelPos(){
        int width, panel1Width;

        panel1Width = jPanel1.getWidth();
        width = jPanel3.getWidth();

        Point tmp = new Point();
        Point tmp1 = new Point();

        tmp = jPanel3.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel10.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel3.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel4.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel3.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel4.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel3.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel4.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel5.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel4.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel5.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel4.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel5.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel6.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel5.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel6.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel5.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel6.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel7.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel6.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel7.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel6.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel7.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel8.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel7.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel8.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel7.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel8.setLocation(tmp);
            //set the new pos coming from the right
        }
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel9.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel8.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel9.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel8.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel9.setLocation(tmp);
            //set the new pos coming from the right
        }
        //else if (tmp.x > panel1Width - width/2 ){
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel10.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel9.setLocation(tmp);
            //set the new pos coming from the left
        }

        tmp = jPanel10.getLocation();
        if (tmp.x+width/2 < -138 ){
            tmp1 = jPanel9.getLocation();
            System.out.println("set the new pos coming from the right");
            tmp.x = tmp1.x + 158;
            jPanel10.setLocation(tmp);
            //set the new pos coming from the right
        }
        //else if (tmp.x > panel1Width - width/2 ){
        else if (tmp.x > panel1Width + 90 ){
            tmp1 = jPanel3.getLocation();
            System.out.println("set the new pos coming from the left");
            tmp.x = tmp1.x - 158;
            jPanel10.setLocation(tmp);
        }
    }
    //[235,233,237] = original color
}