package tbaclient;


import TBA.Data.Entry;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DayPanel.java
 *
 * Created on 18/08/2009, 2:08:14 PM
 */

/**
 *
 * @author Joe
 * @author Dan McGrath
 */
public class DayPanel extends javax.swing.JPanel {
    private Vector<Entry> entries = null;
    private Vector<hourPanel> hourVector = new Vector<hourPanel>();
    private Calendar cal = Calendar.getInstance();

   public void setFadeLeft(JLabel fadeLeft, JLabel fadeRight)
   {
      for(hourPanel aHour : hourVector)
      {
         aHour.setFadeLeft(fadeLeft, fadeRight);
      }
   }

    /** Creates new form DayPanel */
    public DayPanel() {
        initComponents();
        setHourVector();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      hourPanel1 = new tbaclient.hourPanel();
      hourPanel2 = new tbaclient.hourPanel();
      hourPanel3 = new tbaclient.hourPanel();
      hourPanel4 = new tbaclient.hourPanel();
      hourPanel5 = new tbaclient.hourPanel();
      hourPanel6 = new tbaclient.hourPanel();
      hourPanel7 = new tbaclient.hourPanel();
      hourPanel8 = new tbaclient.hourPanel();
      hourPanel9 = new tbaclient.hourPanel();
      hourPanel10 = new tbaclient.hourPanel();
      hourPanel11 = new tbaclient.hourPanel();
      hourPanel12 = new tbaclient.hourPanel();

      setPreferredSize(new java.awt.Dimension(145, 436));
      setLayout(new java.awt.GridLayout(0, 1));

      jLabel1.setText("jLabel1");
      add(jLabel1);

      hourPanel1.setBorder(null);
      add(hourPanel1);

      hourPanel2.setBorder(null);
      add(hourPanel2);

      hourPanel3.setBorder(null);
      add(hourPanel3);

      hourPanel4.setBorder(null);
      add(hourPanel4);

      hourPanel5.setBorder(null);
      add(hourPanel5);

      hourPanel6.setBorder(null);
      add(hourPanel6);

      hourPanel7.setBorder(null);
      add(hourPanel7);

      hourPanel8.setBorder(null);
      add(hourPanel8);

      hourPanel9.setBorder(null);
      add(hourPanel9);

      hourPanel10.setBorder(null);
      add(hourPanel10);

      hourPanel11.setBorder(null);
      add(hourPanel11);

      hourPanel12.setBorder(null);
      add(hourPanel12);
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private tbaclient.hourPanel hourPanel1;
   private tbaclient.hourPanel hourPanel10;
   private tbaclient.hourPanel hourPanel11;
   private tbaclient.hourPanel hourPanel12;
   private tbaclient.hourPanel hourPanel2;
   private tbaclient.hourPanel hourPanel3;
   private tbaclient.hourPanel hourPanel4;
   private tbaclient.hourPanel hourPanel5;
   private tbaclient.hourPanel hourPanel6;
   private tbaclient.hourPanel hourPanel7;
   private tbaclient.hourPanel hourPanel8;
   private tbaclient.hourPanel hourPanel9;
   private javax.swing.JLabel jLabel1;
   // End of variables declaration//GEN-END:variables


   public Vector<Entry> getEntries() {
        return entries;
    }

    public void setEntries(Vector<Entry> entries) {
        this.entries = entries;
        if (entries != null){
            for (int i = 0; i < hourVector.size(); i++)
            {
               if (i < entries.size())
               {
                  hourVector.elementAt(i).setEntry(entries.get(i));
               }
               else
               {
                  hourVector.elementAt(i).setEntry(null);
               }

            }  
        }
        else
        {
            for (int i = 0; i < hourVector.size(); i++) {
                hourVector.elementAt(i).setEntry(null);
            }
        }
    }

    public Calendar getDate() {
        return cal;
    }

    public void increaseDate() {
        cal.add(Calendar.DAY_OF_YEAR, 8);
        setDate(cal);
    }

    public void decreaseDate() {
        cal.add(Calendar.DAY_OF_YEAR, -8);
        setDate(cal);
    }

    public void setDate(Calendar tmpCal) {
        String day, month, year, date;
        this.cal = tmpCal;
        Date tmp = tmpCal.getTime();
        System.out.println(tmp.toString());
        date = tmp.toString().substring(8, 10);
        month = tmp.toString().substring(4, 7);
        year = tmp.toString().substring(23, 28);
        day = tmp.toString().substring(0, 3);
        //date = date.concat(year);
        //date = date.substring(1, 10)
        jLabel1.setText(day+" "+date+"/"+month+"/"+year);
    }

    private void setHourVector() {
        hourVector.add(hourPanel1);
        hourVector.add(hourPanel2);
        hourVector.add(hourPanel3);
        hourVector.add(hourPanel4);
        hourVector.add(hourPanel5);
        hourVector.add(hourPanel6);
        hourVector.add(hourPanel7);
        hourVector.add(hourPanel8);
        hourVector.add(hourPanel9);
        hourVector.add(hourPanel10);
        hourVector.add(hourPanel11);
        hourVector.add(hourPanel12);
    }

}
